### ISSUE TITLE
load_conv_bn2caffe

### ISSUE THREAD

**Issue by ljh9999** [passion3394/darknet2caffe_yolov3#1]
Hello, I was running darknet2caffe.py when I got stuck in load_conv_bn2caffe and made an error of 'total size of new array must be unchanged'. How should this error be solved? I put the CPP, cu and HPP of upsample into the specified folder of caffe and recompiled caffe. Thank you for your reply!

**Comment by passion3394** [comment]
It's long time since my last build. You can reference make_method_by_laymu.txt in the code, which contains some places to modify. Maybe you can post the whole error information, so that I will help to find the reason.

**Comment by ljh9999** [comment]
Hello, the yolo_layer.cpp file is running caffemodel, but I have not been able to convert yolo's original weights file to caffemodel, which means that the yolov3_darknet2caffe.py file in your model_convert folder failed to run. Can I add your WeChat or QQ to facilitate contact?

**Comment by passion3394** [comment]
It's my fault, I didn't use the yolov3_darknet2caffe.py in this code. I have used another version of yolov3_darknet2caffe.py. I think I should upload the script to this repo. My QQ is 339451128.

**Comment by ljh9999** [comment]
What is your real name? I encountered this problem while adding your friends.

**Comment by passion3394** [comment]
I have canceled the question.Try again?

**Comment by ljh9999** [comment]
Sorry to bother you again, I would like to ask if you have used the pre-training weight of darknet53.conv.74 to generate weights files and then convert caffemodel? I had a problem converting my own model. How do you train a model that fits your data set?

**Comment by passion3394** [comment]
Maybe you could create another issue?
